from LLM_patch_generation.args_parser import parse_arguments_validator
from LLM_patch_generation.generator_utils import ask_LLM
from LLM_patch_generation.extract_info.env_scanner import extract_environment_info
from LLM_patch_generation.extract_info.container_scanner import extract_container_info, list_containers
from LLM_patch_generation.validator_utils import search_for, generate_validator_prompt
from LLM_patch_generation.extract_info.vuln_details_extractor import extract_vulnerability_details
import os
import re
import time
import json

# LLM model tasked to validate generated correction patches
VALIDATOR_MODEL = "gpt-5.1"
VALIDATOR_OUTPUT_DIR = "validator_output"

def main():
    # Setting directory containing correction patches
    args = parse_arguments_validator()
    patches_filepath = args.Patches_directory_filepath

    # Automatically identify the OpenVAS CSV report in the patch directory
    csv_files = [f for f in os.listdir(patches_filepath) if f.endswith('.csv') and not f.startswith('.')]
    if not csv_files:
        print(f"Error: No CSV report file found in directory {patches_filepath}. Ending program.")
        return
    report_filepath = os.path.join(patches_filepath, csv_files[0])

    # Specifying targeted vulnerability 
    print('Identifying vulnerability...')
    nvt_oid = None
    try:
        with open(f'{patches_filepath}/gemini-3-flash_details.txt', 'r') as f:
            for line in f:
                if line.startswith('NVT OID:'):
                    nvt_oid = line.split(':', 1)[1].strip()
                    break
    except FileNotFoundError:
        print("Could not find directory containing correction patches. Ending program.")
        return

    if not nvt_oid:
        print("Error: Could not find NVT OID in gemini-3-flash_details.txt. Ending program.")
        return

    # Fetching OpenVAS report
    print('Fetching OpenVAS report...')
    try:
        VULN_DETAILS = extract_vulnerability_details(report_filepath, nvt_oid)
    except (FileNotFoundError, ValueError) as e:
        print(f'Error fetching OpenVAS report details: {str(e)}. Ending program.')
        return

    # Extract environment information from deepseek detail file
    print('Extracting environment information...')
    deepseek_filename = 'deepseek-V3.1_details.txt'
    deepseek_filepath = os.path.join(patches_filepath, deepseek_filename)
    if not os.path.exists(deepseek_filepath):
        deepseek_filename = 'deepseek_v3_details.txt'
        deepseek_filepath = os.path.join(patches_filepath, deepseek_filename)

    try:
        with open(deepseek_filepath, 'r', encoding='utf-8') as f:
            details_content = f.read()
    except FileNotFoundError:
        print(f"Could not find {deepseek_filename} in {patches_filepath}. Ending program.")
        return

    env_match = re.search(r'Env info:\s*(.*)', details_content, re.DOTALL)
    if env_match:
        ENVIRONMENT_INFORMATION = env_match.group(1).strip()
    else:
        print(f"Could not find 'Env info:' in {deepseek_filename}. Ending program.")
        return

    
    # Storing all generated correction patches in a single variable
    print('Gathering generated correction patches...')
    MODELS = ['gemini-2.5-flash', 'gemini-3-flash', 'deepseek-V3.1']
    patches = {}

    for model in MODELS:
        try:
            with open(f'{patches_filepath}/{model}_patch.sh', 'r') as f:
                content = f.read()
                patches[model] = content
        except FileNotFoundError:
            print(f"Could not find correction patch generated by {model}. Ending program.")
            return

        if not content.strip():
            print(f"Error: Correction patch generated by {model} is empty. Ending program.")
            return
    
    GENERATED_CORRECTION_PATCHES = ''
    GENERATED_CORRECTION_PATCHES +=  f'===============================================================================\n'
    for model, patch in patches.items():
        GENERATED_CORRECTION_PATCHES +=  f'CORRECTION PATCH GENERATED BY {model}:\n\n'
        GENERATED_CORRECTION_PATCHES +=  f'{patch}\n'
        GENERATED_CORRECTION_PATCHES +=  f'===============================================================================\n'
    
    # Fully assembling prompt to feed the validator
    validator_prompt = generate_validator_prompt(ENVIRONMENT_INFORMATION, VULN_DETAILS, GENERATED_CORRECTION_PATCHES)
    
    timer_start = time.perf_counter()

    # Sending prompt to validator API
    print(f"Requesting verdict from {VALIDATOR_MODEL}...")
    response = ask_LLM("gpt-5.1", validator_prompt)

    if response.status == "ERR":
        print(f"ERROR while fetching response. Shutting down script.")
        print(f"ERROR details: {response.content}")
        return

    timer_end = time.perf_counter()
    elapsed_time = (timer_end - timer_start)
    
    # Saving validator verdict and prompt
    print("Saving validator output...")
    output_dir = os.path.join(VALIDATOR_OUTPUT_DIR, nvt_oid)
    try:
        os.makedirs(output_dir, exist_ok=True)
    except Exception as e:
        print(f"Could not create directory {output_dir}: {str(e)}")
        return

    # Save verdict
    with open(os.path.join(output_dir, "verdict.txt"), "w", encoding='utf-8') as f:
        f.write(response.content)
        f.write(f"\n\nELAPSED TIME: {elapsed_time}")
        print(f"Verdict successfully saved at {output_dir}/verdict.txt!")

    # Save prompt
    with open(os.path.join(output_dir, "prompt.txt"), "w", encoding='utf-8') as f:
        f.write(validator_prompt)
        print(f"Prompt successfully saved at {output_dir}/prompt.txt!")

    
if __name__ == '__main__':
   main()
